### ISSUE TITLE
Disallowed certain item types on actors

### ISSUE THREAD

**Issue by asacolips** [asacolips-projects/pbta#88]
In GitLab by @Asacolips on Sep 26, 2023, 09:16

Reported by Mana in the Foundry discord:

- Invalid item types are allowed on both characters and NPCs. For example, npcMoves on characters and moves on NPCs. Update the actor class to prevent invalid item types from being added.
- Additionally, tagging seems to have a bug:

```
actor-sheet.js:698 Uncaught (in promise) TypeError: tag.toLowerCase is not a function
    at PbtaActorNpcSheet._activateTagging (actor-sheet.js:698:25)
    at PbtaActorNpcSheet.activateListeners (actor-sheet.js:421:12)
    at PbtaActorNpcSheet._render (foundry.js:5783:10)
    at async PbtaActorNpcSheet._render (foundry.js:6473:5)
```

- Lastly, investigate using `Set` rather than the array structure used on that portion of the code.

**Comment by asacolips** [comment]
In GitLab by @mclemente on Nov 13, 2023, 20:57

mentioned in commit mclemente/pbta@86228c6b0ed52478c195d31b3b6e50d799e0c9cc

**Comment by asacolips** [comment]
In GitLab by @mclemente on Nov 13, 2023, 20:59

mentioned in commit b04957be8a48c8232e96a67a249422d24b3b6a29
