### ISSUE TITLE
Clocks are not working

### ISSUE THREAD

**Issue by asacolips** [asacolips-projects/pbta#90]
In GitLab by @philote on Nov 21, 2023, 23:32

Foundry Version: 11.315

PbtA Version: 0.7.3

New world, no other mods, using the TOML from here: https://asacolips.gitbook.io/pbta-system/pbta-sheet-presets-and-examples/apocalypse-world

```
caught (in promise) ReferenceError: deepclone is not defined
    at PbtaActorSheet._onClockClick (actor-sheet.js:469:16)
    at HTMLInputElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
```

![image](https://gitlab.com/asacolips-projects/foundry-mods/pbta/uploads/bd8e92ff9bce0fbe59fee9020fe102d8/image.png)

**Comment by asacolips** [comment]
In GitLab by @mclemente on Nov 22, 2023, 12:24

Fixed by !47.

**Comment by asacolips** [comment]
In GitLab by @mclemente on Nov 22, 2023, 12:25

mentioned in commit 4d57a04ab55deee3ebb27a787af835cb5cee2a53

**Comment by asacolips** [comment]
In GitLab by @s.paquay1 on Nov 23, 2023, 10:10

mentioned in commit 357a677be40ec75a2ab96fb032e810a774abd09e

**Comment by asacolips** [comment]
In GitLab by @s.paquay1 on Dec 6, 2023, 09:29

mentioned in commit f7b1d934ae76fc9d43ac57f714f76acd7447d433
