### ISSUE TITLE
Forward and Ongoing character sheet set up not working

### ISSUE THREAD

**Issue by asacolips** [asacolips-projects/pbta#99]
In GitLab by @Lwgamble on Dec 14, 2023, 12:44

Hi,
Noticed last night that the Forward and Ongoing attributes on the character sheet aren't working in our Sprawl Game so I've taken a clean load of V8.0 running on V11 build 315 and loaded the standard sheet from the Getting started wiki.
Created a new basic move - the move rolls expected dice as normal, but as soon as the Foward or Ongoing counters are set to non 0 value, the roll does nothing, same behaviour as the sprawl game. No other modules were running - this is the error in the console

rolls.js:123 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'push')
[Detected 1 package: system:pbta]
    at RollPbtA.configureModifiers (rolls.js:123:31)
    at RollPbtA.configureDialog (rolls.js:240:10)
    at ItemPbta.roll (item.js:106:30)
    at ActorPbta._onRoll (actor.js:164:12)
    at PbtaActorSheet._onRollable (actor-sheet.js:639:16)
    at HTMLSpanElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)

**Comment by asacolips** [comment]
In GitLab by @Asacolips on Dec 14, 2023, 15:08

@Lwgamble this should be resolved as part of the 0.8.1 release in !56. I'll verify before closing this, but I expect 0.8.1 will release in the next few days.

**Comment by asacolips** [comment]
In GitLab by @Asacolips on Dec 15, 2023, 14:37

Verified this will be resolved in 0.8.1
